name: Deploy to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd backend
        npm ci
    
    - name: Run tests before deploy
      run: |
        cd backend
        npm test
    
    - name: Deploy to Railway
      uses: railway/deploy@v1
      with:
        service: OmniBoard-Backend
        token: ${{ secrets.RAILWAY_TOKEN }}
    
    - name: Health check
      run: |
        echo "Waiting for deployment to complete..."
        sleep 30
        
        # Get Railway URL from Railway CLI or environment
        RAILWAY_URL="https://omniboard-backend-production.up.railway.app"
        
        echo "Testing health endpoint: $RAILWAY_URL/health"
        curl -f "$RAILWAY_URL/health" || exit 1
        
        echo "Testing API endpoint: $RAILWAY_URL/api/v1"
        curl -f "$RAILWAY_URL/api/v1" || exit 1
        
        echo "✅ Deployment successful!"
